package auth

import "time"

type RegisterRequest struct {
	Name     string `json:"name" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=3"`
	Code     string `json:"code" binding:"required,len=6"`
}

type LoginRequest struct {
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=3"`
}

type User struct {
	ID              uint       `gorm:"primaryKey" json:"id"`
	Name            string     `json:"name"`
	Email           string     `gorm:"uniqueIndex" json:"email"`
	Password        string     `json:"-"`
	Role            string     `gorm:"type:varchar(20);default:user" json:"role"`
	AvatarURL       string     `json:"avatar_url"`
	AccessBlocked   bool       `gorm:"default:false" json:"access_blocked"`
	AccessBlockedAt *time.Time `json:"access_blocked_at,omitempty"`
	LastActiveAt    time.Time  `gorm:"not null;default:CURRENT_TIMESTAMP" json:"last_active_at"`
}

type UserMetricsResponse struct {
	Total   int64 `json:"total"`
	Active  int64 `json:"active"`
	Blocked int64 `json:"blocked"`
	Admins  int64 `json:"admins"`
}

type PasswordResetToken struct {
	ID        uint      `gorm:"primaryKey" json:"id"`
	UserID    uint      `gorm:"index" json:"user_id"`
	Email     string    `gorm:"index" json:"email"`
	IPAddress string    `gorm:"index" json:"ip_address"`
	CodeHash  string    `json:"-"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type RegistrationCode struct {
	ID        uint      `gorm:"primaryKey" json:"id"`
	Email     string    `gorm:"index" json:"email"`
	CodeHash  string    `json:"-"`
	IPAddress string    `gorm:"index" json:"ip_address"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `gorm:"default:false" json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type RequestRegisterCodeRequest struct {
	Email string `json:"email" binding:"required,email"`
	BotProtectionRequest
}

type ForgotPasswordRequest struct {
	Email string `json:"email" binding:"required,email"`
	BotProtectionRequest
}

// BotProtectionRequest carries an attestation generated by the client. Tokens
// are transient and must never be persisted or written to application logs.
type BotProtectionRequest struct {
	ProtectionProvider string `json:"protection_provider" binding:"omitempty,oneof=turnstile play_integrity"`
	TurnstileToken     string `json:"turnstile_token" binding:"omitempty,max=20000"`
	PlayIntegrityToken string `json:"play_integrity_token" binding:"omitempty,max=20000"`
}

type ResetPasswordRequest struct {
	Email       string `json:"email" binding:"required,email"`
	Code        string `json:"code" binding:"required,len=6"`
	NewPassword string `json:"new_password" binding:"required,min=3"`
}

type DeleteUserRequest struct {
	ID uint `json:"id" binding:"required"`
}
